### PR TITLE
Create proposal jobs for network_content_collector

### PR DESCRIPTION
**Pull request by pabelanger**
Each time we update network_content_collector, generate new PRs for our
collections on github.com.

Signed-off-by: Paul Belanger <pabelanger@redhat.com>

### CODE REVIEW

**Comment by CaptTrews** [comment]
rehceck

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now 1ed10191120ee1cf8b2411689325eafc02cb2cfe

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now ba0f5fdbdd29204026174e98e35fe3ae02c773c5

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now 1a03c4d6ba0d5c5a2a9b94ea01cba902b4c44d27

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now 0273d313ff3da9a4c99644a0699571f139f969b4

**Pull request merged**
